userAssets=[
  {"d":"audio",
   "f":[
    "footstep_carpet_000.ogg",
    "Hello.ogg"
  ]},
  {"d":"curated",
   "f":[
    {"d":"characters",
     "f":[
      {"d":"Suit",
       "f":[
        "Suit.gltf",
        "thumbnail.png"
      ]}
    ]},
    {"d":"skyboxes",
     "f":[
      {"d":"city",
       "f":[
        "city_nx.jpg",
        "city_ny.jpg",
        "city_nz.jpg",
        "city_px.jpg",
        "city_py.jpg",
        "city_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"desert",
       "f":[
        "desert_nx.jpg",
        "desert_ny.jpg",
        "desert_nz.jpg",
        "desert_px.jpg",
        "desert_py.jpg",
        "desert_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"dusk",
       "f":[
        "dusk_nx.jpg",
        "dusk_ny.jpg",
        "dusk_nz.jpg",
        "dusk_px.jpg",
        "dusk_py.jpg",
        "dusk_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"hilly",
       "f":[
        "hilly_nx.jpg",
        "hilly_ny.jpg",
        "hilly_nz.jpg",
        "hilly_px.jpg",
        "hilly_py.jpg",
        "hilly_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"hot",
       "f":[
        "hot_nx.jpg",
        "hot_ny.jpg",
        "hot_nz.jpg",
        "hot_px.jpg",
        "hot_py.jpg",
        "hot_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"moon",
       "f":[
        "moon_nx.jpg",
        "moon_ny.jpg",
        "moon_nz.jpg",
        "moon_px.jpg",
        "moon_py.jpg",
        "moon_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"none",
       "f":[
        "thumbnail.png"
      ]},
      {"d":"rain",
       "f":[
        "rain_nx.jpg",
        "rain_ny.jpg",
        "rain_nz.jpg",
        "rain_px.jpg",
        "rain_py.jpg",
        "rain_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"snow1",
       "f":[
        "snow1_nx.jpg",
        "snow1_ny.jpg",
        "snow1_nz.jpg",
        "snow1_px.jpg",
        "snow1_py.jpg",
        "snow1_pz.jpg",
        "thumbnail.png"
      ]},
      {"d":"TropicalSunnyDay",
       "f":[
        "thumbnail.png",
        "TropicalSunnyDay_nx.jpg",
        "TropicalSunnyDay_ny.jpg",
        "TropicalSunnyDay_nz.jpg",
        "TropicalSunnyDay_px.jpg",
        "TropicalSunnyDay_py.jpg",
        "TropicalSunnyDay_pz.jpg"
      ]}
    ]}
  ]}
]